class Error(Exception):
    pass

class CoreError(Error):
    pass
